#Install CloudBoost Engine

apiVersion: v1
kind: Service
metadata:
  labels:
    name: cloudboost-engine
  name: cloudboost-engine
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4730
    nodePort: 30730
  selector:
    name: cloudboost-engine
---

#Install CloudBoost Engine Replication Controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cloudboost-engine
  name: cloudboost-engine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudboost-engine
    spec:
      containers:
      - image: cloudboost/cloudboost
        name: cloudboost-engine
        ports:
        - name: cloudboost
          containerPort: 4730
          hostPort: 4730
---

#Install CloudBoost User Service

apiVersion: v1
kind: Service
metadata:
  labels:
    name: cloudboost-user-service
  name: cloudboost-user-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001
  selector:
    name: cloudboost-user-service
---

#Install CloudBoost User Service Replication Controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cloudboost-user-service
  name: cloudboost-user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudboost-user-service
    spec:
      containers:
      - image: registry.cloudboost.io/cloudboost-service
        name: cloudboost-user-service
        ports:
        - name: cloudboost
          containerPort: 3000
          hostPort: 3000
---

#Install CloudBoost Dashboard

apiVersion: v1
kind: Service
metadata:
  labels:
    name: cloudboost-dashboard
  name: cloudboost-dashboard
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 1440
    nodePort: 30040
  selector:
    name: cloudboost-dashboard
---

#Install CloudBoost Dashboard Replication Controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cloudboost-dashboard
  name: cloudboost-dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudboost-dashboard
    spec:
      containers:
      - image: registry.cloudboost.io/cloudboost-dashboard
        name: cloudboost-dashboard
        ports:
        - name: cloudboost
          containerPort: 1440
          hostPort: 1440
---
