#Install CloudBoost Engine

apiVersion: v1
kind: Service
metadata:
  labels:
    name: cloudboost-engine
  name: cloudboost-engine
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4730
    nodePort: 30730
  selector:
    name: cloudboost-engine
---

#Install CloudBoost Engine Replication Controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cloudboost-engine
  name: cloudboost-engine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudboost-engine
    spec:
      containers:
      - image: cloudboost/cloudboost
        name: cloudboost-engine
        ports:
        - name: cloudboost
          containerPort: 4730
          hostPort: 4730
---
